const BALANCE_LOOP_PREFIX="B";
const CLOCKWISE_LINK="images/clockWise.svg";


const REINFORCEMENT_LOOP_PREFIX="R";
const COUNTERCLOCKWISE_LINK="images/counterClockWise.svg";


const POSITIVE_LINK_VALUE='1';
const POSITIVE_BY_TIME_LINK_VALUE='2';
const NEGATIVE_LINK_VALUE='3';
const NEGATIVE_BY_TIME_LINK_VALUE='4';

const BALANCE_LOOP_CLOCKWISE='1';
const BALANCE_LOOP_COUNTERCLOCKWISE='2';
const REINFORCEMENT_LOOP_CLOCKWISE='3';
const REINFORCEMENT_LOOP_COUNTERCLOCKWISE='4';