const DATA_RECTANGLE_WIDTH=60;
const DATA_RECTANGLE_HEIGHT=30;

const ELEMENT_RECTANGLE_WIDTH=30;
const ELEMENT_RECTANGLE_HEIGHT=120;

const CLEAR_RECTANGLE_WIDTH=30;
const CLEAR_RECTANGLE_HEIGHT=30;

const DATA_RECTANGLE_IMAGE_SIZE=24;

const BORDER_COLOR="#000";